import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"; // Global header

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Al-Nasri Dental Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-screen bg-gradient-to-br from-gray-900 to-black text-white`}
      >
        <div className="flex flex-col w-full min-h-screen">
          {/* Global Header */}
          <Header />

          {/* Main content */}
          <main className="flex flex-col items-center w-full p-4 sm:p-8">
            <div className="w-full max-w-6xl">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
